name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          git clone https://${GEOIP_TOKEN}@github.com/${GITHUB_REPOSITORY}
          cd log
          go build -v
          go test -v
